//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emprestimo()
        {
            this.Devolucao = new HashSet<Devolucao>();
            this.Renovacao = new HashSet<Renovacao>();
        }
    
        public int Id { get; set; }
        public int LocacaoId { get; set; }
        public int ExemplarId { get; set; }
        public System.DateTime DataPrevistaDevolucao { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucao> Devolucao { get; set; }
        public virtual Exemplar Exemplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renovacao> Renovacao { get; set; }
        public virtual Locacao Locacao { get; set; }
    }
}
