//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locacao()
        {
            this.Emprestimo = new HashSet<Emprestimo>();
        }
    
        public int Id { get; set; }
        public int UsuarioFinalId { get; set; }
        public int BibliotecarioId { get; set; }
        public System.DateTime DataLocacao { get; set; }
    
        public virtual Bibliotecario Bibliotecario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprestimo> Emprestimo { get; set; }
        public virtual UsuarioFinal UsuarioFinal { get; set; }
    }
}
