//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SYSLIBRARY_DBEntities : DbContext
    {
        public SYSLIBRARY_DBEntities()
            : base("name=SYSLIBRARY_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Bibliotecario> Bibliotecario { get; set; }
        public virtual DbSet<Devolucao> Devolucao { get; set; }
        public virtual DbSet<Editora> Editora { get; set; }
        public virtual DbSet<Emprestimo> Emprestimo { get; set; }
        public virtual DbSet<Exemplar> Exemplar { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Locacao> Locacao { get; set; }
        public virtual DbSet<Renovacao> Renovacao { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioFinal> UsuarioFinal { get; set; }
        public virtual DbSet<Obra> Obra { get; set; }
    }
}
