//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObraEntity()
        {
            this.Exemplar = new HashSet<ExemplarEntity>();
        }
    
        public int Id { get; set; }
        public int GeneroId { get; set; }
        public int EditoraId { get; set; }
        public string Nome { get; set; }
        public string Autor { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual EditoraEntity Editora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExemplarEntity> Exemplar { get; set; }
        public virtual GeneroEntity Genero { get; set; }
    }
}
