//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioFinalEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioFinalEntity()
        {
            this.Locacao = new HashSet<LocacaoEntity>();
        }
    
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public bool Pendencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocacaoEntity> Locacao { get; set; }
        public virtual UsuarioEntity Usuario { get; set; }
    }
}
