//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenovacaoEntity
    {
        public int Id { get; set; }
        public int EmprestimoId { get; set; }
        public System.DateTime DataRenovacao { get; set; }
        public System.DateTime DataPrevistaDevolucao { get; set; }
    
        public virtual EmprestimoEntity Emprestimo { get; set; }
    }
}
