//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SYSLIBRARY_DBEntities : DbContext
    {
        public SYSLIBRARY_DBEntities()
            : base("name=SYSLIBRARY_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BibliotecarioEntity> Bibliotecario { get; set; }
        public virtual DbSet<DevolucaoEntity> Devolucao { get; set; }
        public virtual DbSet<EditoraEntity> Editora { get; set; }
        public virtual DbSet<EmprestimoEntity> Emprestimo { get; set; }
        public virtual DbSet<ExemplarEntity> Exemplar { get; set; }
        public virtual DbSet<GeneroEntity> Genero { get; set; }
        public virtual DbSet<LocacaoEntity> Locacao { get; set; }
        public virtual DbSet<ObraEntity> Obra { get; set; }
        public virtual DbSet<RenovacaoEntity> Renovacao { get; set; }
        public virtual DbSet<TipoUsuarioEntity> TipoUsuario { get; set; }
        public virtual DbSet<UsuarioEntity> Usuario { get; set; }
        public virtual DbSet<UsuarioFinalEntity> UsuarioFinal { get; set; }
    }
}
